# Generated by Django 6.0.1 on 2026-02-05 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliverytask'),
        ('donations', '0002_donation_is_available_alter_donation_donor'),
        ('requests', '0002_remove_foodrequest_is_fulfilled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='picked_at',
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donation'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.foodrequest'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
