# Generated by Django 6.0.1 on 2026-02-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_deliverytask_delivered_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryTask',
        ),
    ]
