# Generated by Django 6.0.1 on 2026-02-05 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrequest',
            name='is_fulfilled',
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='urgency',
            field=models.CharField(max_length=50),
        ),
    ]
