# Generated by Django 6.0.1 on 2026-02-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_foodrequest_is_fulfilled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
    ]
