# Generated by Django 6.0.1 on 2026-02-05 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_foodrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='foodrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
